{
 "title": "Workshop sample-app Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(http_error_count{canary=~\"baseline|canary\"} / http_request_count{canary=~\"baseline|canary\"}) by (canary)"
    }
   ]
  },
  {
   "title": "Job Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(job_processing_time{canary=~\"baseline|canary\"}) by (canary)"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(network_latency{canary=~\"baseline|canary\"}) by (canary)"
    }
   ]
  }
 ]
}